export const FETCH_ITEMS = 'NEWS#FETCH_ITEMS';
export const RECEIVE_ITEMS_DONE = 'NEWS#RECEIVE_ITEMS_DONE';

export const FETCH_ITEM = 'NEWS#FETCH_ITEM';
export const RECEIVE_ITEM_DONE = 'NEWS#RECEIVE_ITEM_DONE';

export const FETCH_FILTERS = 'NEWS#FETCH_FILTERS';
export const RECEIVE_FILTERS_DONE = 'NEWS#RECEIVE_FILTERS_DONE';

export const FETCH_COUNT = 'NEWS#FETCH_COUNT';
export const RECEIVE_COUNT_DONE = 'NEWS#RECEIVE_COUNT_DONE';
