const { release } = require('../options');

module.exports = {
  stats: {
    colors: true,
    source: true,
    assets: true,
    errors: true,
    errorDetails: true,
    warnings: true,
    all: false,
    builtAt: true,
    hash: true,
    version: false,
    timings: false,
    entrypoints: true,
    cached: false,
    chunks: true,
    chunkGroups: false,
    chunkModules: false,
    chunkOrigins: false,
    moduleAssets: false,
    cachedAssets: false,
    children: false,
    moduleTrace: false,
    assets: true,
    modules: true,
    publicPath: false,
    performance: true,
    runtimeModules: false,
    groupAssetsByPath: true,
    groupAssetsByEmitStatus: false,
  },
};
