// require('whatwg-fetch')
// require('intl')
// require('url-polyfill')
// require('core-js/web/dom-collections')
// require('core-js/es6/map')
// require('core-js/es6/string')
// require('core-js/es6/array')
// require('core-js/es6/object')
