module.exports.configs = {
  html5: true,
  keepClosingSlash: true,
  caseSensitive: false,
  removeComments: true,
  decodeEntities: true,
  sortClassName: false,
  sortAttributes: false,
  customAttrAssign: true,
  collapseWhitespace: true,
  removeTagWhitespace: false,
  removeAttributeQuotes: true,
  removeEmptyAttributes: false,
  preventAttributesEscaping: false,
  processConditionalComments: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  collapseInlineTagWhitespace: false,
  collapseBooleanAttributes: true,
  trimCustomFragments: true,
  useShortDoctype: true,
  minifyJS: true,
  minifyCSS: true,
  minifyURLs: true,
  customAttrSurround: ['async', 'defer', 'checked', 'disabled', 'readonly', 'crossorigin'],
}
