module.exports.configs = {
  html5: true,
  caseSensitive: true,
  removeComments: true,
  keepClosingSlash: true,
  decodeEntities: true,
  sortAttributes: true,
  sortClassName: false,
  customAttrAssign: true,
  collapseWhitespace: true,
  removeTagWhitespace: false,
  removeAttributeQuotes: true,
  removeEmptyAttributes: false,
  preventAttributesEscaping: true,
  processConditionalComments: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  collapseInlineTagWhitespace: true,
  collapseBooleanAttributes: true,
  trimCustomFragments: true,
  useShortDoctype: true,
  minifyJS: true,
  minifyCSS: true,
  minifyURLs: true,
  customAttrSurround: ['async', 'defer', 'checked', 'disabled', 'readonly'],
}
